apiVersion: v1
kind: Secret

metadata:
  name: autotube-secrets

type: Opaque

stringData:
  ASSEMBLYAI_API_KEY: "your-key"
  OPENAI_API_KEY: "your-key"
  ELEVEN_LABS_API_KEY: "your-key"

  DATABASE_URL: "your-db-url"

  AZURE_STORAGE_ACCOUNT_NAME: "your-storage-name"
  AZURE_STORAGE_ACCOUNT_KEY: "your-storage-key"
  AZURE_STORAGE_CONTAINER_NAME: "your-container-name"
  AZURE_STORAGE_CONNECTION_STRING: "your-connection-string"

  THUMBNAIL_STORAGE_CONNECTION_STRING: "your-thumbnail-storage"
  THUMBNAIL_STORAGE_ACCOUNT_NAME: "your-thumbnail-account"

  AZURE_QUEUE_NAME: "your-queue-name"
  AZURE_QUEUE_P2_TEXT_TO_CONTENT_WORKER: "your-worker-queue"

  JWT_SECRET_KEY: "your-secret"