apiVersion: v1
kind: Service

metadata:
  name: autotube-worker2-service

spec:
  type: ClusterIP

  selector:
    app: autotube-worker2

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
